Bedrock-Layouts/Bedrock

src/index.mdx

Fix typo on homepage

---

src/inspiration.mdx
src/primitives.mdx

Hey! Been using this for rapid prototypes / my personal blog and enjoying it so far. When initially looking around, I saw a couple small things that could optionally be enhanced to improve flow and the reader's experience. Feel free to close if not needed :) .
Also might be cool to add a 'Reels' type primitive or something with `scroll-snap` gaining popularity.. if i get some free time I'll throw it up in another pr

Tweak docs for readability

---

package-lock.json
packages/use-forwarded-ref/README.md
src/components/useForwardedRef.mdx

fix documentation

---

.husky/prepare-commit-msg
.travis.yml
CHANGELOG.md
README.md
lerna.json
package-lock.json
package.json

docs: add commitizen initegration

---

CONTRIBUTING.md

This is used to fix some grammar errors found in the contributing doc

docs(contributing.md): fix grammar errors

---

packages/spacing-constants/src/index.tsx
packages/stack/__tests__/__snapshots__/stack.test.js.snap
packages/stack/__tests__/stack.test.js

In order to comply with the System UI Theme Specification we are accepting both "spacing" and
"space"
#542

feat(spacing-constants): update to accept space as a key on the theme

---

.storybook/pages/Landing.stories.mdx
README.md
package-lock.json
packages/appboundary/__tests__/__snapshots__/appboundary.test.js.snap
packages/appboundary/src/index.tsx
packages/center/__tests__/__snapshots__/center.test.js.snap
packages/center/src/index.tsx
packages/grid/__tests__/__snapshots__/grid.test.js.snap
packages/grid/src/index.tsx
packages/masonry-grid/__tests__/__snapshots__/masonary-grid.test.js.snap
packages/spacing-constants/examples/spacing-constants.stories.mdx
packages/switcher/package.json

docs(spacing-constants): update spacing docs to show how to override space key/values

---

package-lock.json
package.json
packages/columns/__tests__/__snapshots__/columns.test.js.snap
packages/columns/__tests__/columns.test.js
packages/columns/examples/Columns.stories.mdx
packages/columns/src/index.tsx

feat(column): add ability to set an offsetStart and offsetEnd to Column

---

package-lock.json
packages/appboundary/__tests__/__snapshots__/appboundary.test.js.snap
packages/appboundary/__tests__/appboundary.test.js
packages/appboundary/src/index.tsx
packages/center/__tests__/__snapshots__/center.test.js.snap
packages/center/src/index.tsx
packages/grid/__tests__/__snapshots__/grid.test.js.snap
packages/grid/src/index.tsx
packages/masonry-grid/__tests__/__snapshots__/masonary-grid.test.js.snap
packages/spacing-constants/__tests__/__snapshots__/spacing-constants.test.js.snap
packages/spacing-constants/__tests__/spacing-constants.test.js
packages/spacing-constants/src/index.tsx

add-size-types

---

.storybook/pages/Landing.stories.mdx
.storybook/pages/contributing.stories.mdx
.storybook/ui-components/Avatar.tsx
CONTRIBUTING.md
README.md
packages/appboundary/examples/AppBoundary.stories.mdx
packages/center/examples/Center.stories.mdx
packages/column-drop/examples/ColumnDrop.stories.mdx
packages/columns/examples/Columns.stories.mdx
packages/cover/examples/Cover.stories.mdx
packages/css-reset/examples/CSSReset.stories.mdx
packages/frame/examples/Frame.stories.mdx
packages/grid/examples/Grid.stories.mdx
packages/inline-cluster/examples/InlineCluster.stories.mdx
packages/inline/examples/Inline.stories.mdx
packages/masonry-grid/examples/MasonryGrid.stories.mdx
packages/padbox/examples/PadBox.stories.mdx
packages/reel/examples/Reel.stories.mdx
packages/split/examples/Split.stories.mdx
packages/stack/examples/Stack.stories.mdx

docs(docs): add names to components and contributors

---

.storybook/pages/Landing.stories.mdx
.storybook/pages/contributing.stories.mdx
.storybook/pages/hero.stories.mdx
.storybook/pages/installation.stories.mdx
.storybook/pages/introduction.stories.mdx
.storybook/pages/menu.stories.mdx
.storybook/pages/spacing.stories.mdx
.storybook/pages/stack.stories.mdx
.storybook/preview.js
packages/bedrock-layout-css/package.json
packages/css-reset/examples/CSSReset.stories.mdx

This change will allow importing and unpkg to automatically return the correct css

build(bedrock-layout-css): update the package.json to allow css to be returned by default

---

.storybook/pages/Landing.stories.mdx
.storybook/pages/hero.stories.mdx
.storybook/pages/installation.stories.mdx
.storybook/pages/introduction.stories.mdx
.storybook/pages/menu.stories.mdx
.storybook/pages/spacing.stories.mdx
.storybook/pages/stack.stories.mdx
examples/web.dev.stories.mdx
packages/bedrock-layout-css/examples/css.stories.mdx
packages/bedrock-layout-css/package.json
packages/css-reset/examples/CSSReset.stories.mdx

While updating the nav layout, some of the nav links broke. This commit should fix that.

docs(docs): fix nav links

---

.storybook/pages/Landing.stories.mdx

One final nav link that needs to be fixed

docs(docs): update broken nav link

---

.storybook/manager.js

The full logo of the brand was broken

docs(doc): fix broken logo image

---

.storybook/pages/contributing.stories.mdx
CONTRIBUTING.md
examples/examples.stories.mdx
packages/bedrock-layout-css/src/components/frame.css
packages/frame/__tests__/__snapshots__/frame.test.js.snap
packages/frame/src/index.tsx

The overflow on the frame element needs to be set to hidden, otherwise the content inside will just
overflow and border-radius won't be visible

fix(frame): fix bug where border-radius was not masking the image

---

package.json
yarn.lock

updating all the dependencies in dependabot

build(docs): update dependencies

---

packages/masonry-grid/src/index.tsx
packages/spacing-constants/src/index.tsx

fix(fix in types): fixing types

---

packages/appboundary/package.json
packages/center/package.json
packages/column-drop/package.json
packages/columns/package.json
packages/cover/package.json
packages/css-reset/package.json
packages/frame/package.json
packages/grid/package.json
packages/inline-cluster/package.json
packages/inline/package.json
packages/masonry-grid/package.json
packages/padbox/package.json
packages/primitives/package.json
packages/reel/package.json
packages/spacing-constants/package.json
packages/split/package.json
packages/stack/package.json
yarn.lock

fix: update peer dependencies to include React 18

---

.storybook/pages/lang/es/Landing.stories.mdx

Hello, @Jarvis1010. This is the first translation

Translating Landing page

---

.storybook/preview.ts
packages/css/examples/Stack.stories.mdx
packages/css/examples/center.stories.mdx
packages/css/examples/column-drop.stories.mdx
packages/css/examples/columns.stories.mdx
packages/css/examples/cover.stories.mdx
packages/css/examples/css-reset.stories.mdx
packages/css/examples/css.stories.mdx
packages/css/examples/frame.stories.mdx
packages/css/examples/grid.stories.mdx
packages/css/examples/inline-cluster.stories.mdx
packages/css/examples/inline.stories.mdx
packages/css/examples/reel.stories.mdx
packages/css/examples/split.stories.mdx
packages/spacing-constants/package.json

incorrectly added open-props as a peer dependency

fix(spacing-contants): fix open-props dependencies

---

packages/css/examples/Component.tsx
packages/css/examples/Stack.stories.mdx
packages/css/examples/column-drop.stories.mdx
packages/css/examples/columns.stories.mdx
packages/css/examples/cover.stories.mdx
packages/css/examples/grid.stories.mdx
packages/css/examples/inline-cluster.stories.mdx
packages/css/examples/inline.stories.mdx
packages/css/examples/reel.stories.mdx
packages/css/examples/split.stories.mdx
packages/css/src/components/column-drop.css
packages/css/src/components/columns.css
packages/css/src/components/cover.css
packages/css/src/components/grid.css
packages/css/src/components/inline-cluster.css
packages/css/src/components/inline.css
packages/css/src/components/reel.css
packages/css/src/components/split.css
packages/css/src/components/stack.css
packages/spacing-constants/__tests__/spacing-constants.test.tsx
packages/spacing-constants/src/index.tsx

spacer components now can use `gutter:[sizeName]`

Add-custom-properties

---

packages/column-drop/src/index.tsx
packages/cover/src/index.tsx
packages/padbox/src/index.tsx
packages/spacing-constants/src/index.tsx

fix problem with declaration merging

fix(spacing): fix DefaultTheme declaration merging

---

.eslintrc
packages/bedrock-layout-css/build.ts
packages/cover/src/index.tsx
packages/css-reset/build.ts
packages/css/build.ts
packages/padbox/__tests__/padbox.test.jsx
packages/padbox/src/index.tsx

This linting rule will help ensure no console logs make it to the final build

fix: add linting rule to prevent console.logs making it to production

---

examples/web.dev.stories.mdx
packages/css/src/components/columns.css
packages/css/src/components/split.css

fix(columns): fix where gutters are calculated

---

package.json
packages/inline/src/index.tsx
packages/spacing-constants/__tests__/spacing-constants.test.tsx
packages/spacing-constants/src/index.tsx

The Switch at property value should accept valid size options values like sizeContent2
fix #1759

Fix-size-props

---

packages/inline/__tests__/__snapshots__/inline.test.tsx.snap
packages/inline/__tests__/inline.test.tsx
packages/inline/src/index.tsx

fixed the logic check where size keywords were not being properly used for the switchAt property

fix(inline): fix logic where switchAt wasn't using size keywords

---

packages/css/src/components/split.css

sometimes split calculations would be off

fix(split): update to css to fix split bug

---

.storybook/manager-styles.css
.storybook/styles.css
package.json
stories/stack/Stack.stories.mdx
yarn.lock

Proof of concept for consolidating css and react stories

docs(docs): start consolidating react and css examples

---

packages/appboundary/src/index.tsx
packages/center/src/index.tsx
packages/column-drop/src/index.tsx
packages/columns/src/index.tsx

refactor: add jsdoc style type definitions to components

---

packages/appboundary/src/index.tsx
packages/center/src/index.tsx
packages/column-drop/src/index.tsx
packages/cover/src/index.tsx
packages/frame/__tests__/__snapshots__/frame.test.tsx.snap
packages/frame/__tests__/frame.test.tsx
packages/frame/src/index.tsx
packages/grid/src/index.tsx
yarn.lock

Ratio can now be a string with 2 numbers and a colon in between. e.g. 1:1

feat(frame): add new string ratio option

---

packages/inline-cluster/src/index.tsx
packages/inline/src/index.tsx
packages/masonry-grid/src/index.tsx
packages/padbox/src/index.tsx
stories/inline/Inline.stories.mdx
stories/masonry-grid/MasonryGrid.stories.mdx

Added JSdoc style comments to provide documentation help

feat: add type descriptions to more components

---

.github/workflows/chromatic.yml

update github actions to use turbosnap

ci(chromatic): use turbo snap in ci

---

stories/reel/Reel.stories.tsx
yarn.lock

docs(reel): update reel stories to show all gutter options

---

examples/examples.stories.mdx
stories/reel/Reel.stories.tsx
yarn.lock

docs(reel): add reel examples

---

.storybook/styles.css
.storybook/ui-components/LocaleFab.tsx
package.json
yarn.lock

docs(docs): remove reach-ui dependencies

---

packages/css/src/components/center.css
packages/css/src/components/column-drop.css
packages/css/src/components/columns.css
packages/css/src/components/cover.css
packages/css/src/components/grid.css
packages/css/src/components/inline.css
packages/css/src/components/split.css
stories/center/Center.stories.tsx
stories/column-drop/ColumnDrop.stories.tsx
stories/columns/Columns.stories.tsx
stories/cover/Cover.stories.tsx
stories/grid/Grid.stories.tsx
stories/inline/Inline.stories.tsx
stories/split/Split.stories.tsx

in the future all custom properties that are considered "public" will be kebab case. This adds
support for that and encourages it's use as the primary use case.  In the next version we will be
removing  camelCase propeties.
re #2207

feat: add support for kebab case properties

---

packages/columns/__tests__/__snapshots__/columns.test.tsx.snap
packages/columns/__tests__/columns.test.tsx
packages/columns/src/index.tsx
packages/css/src/components/columns.css
packages/solid-doc-site/src/pages/ColumnsPage/ColumnsPage.tsx
packages/solid-doc-site/src/pages/ColumnsPage/argTypes.ts
packages/solid-doc-site/src/pages/ColumnsPage/column-playground.tsx
packages/solid-doc-site/src/pages/ColumnsPage/columns.tsx
packages/solid-doc-site/src/pages/ColumnsPage/gutters.tsx
packages/solid-doc-site/src/pages/ColumnsPage/offset.tsx
packages/solid-doc-site/src/pages/ColumnsPage/span.tsx
packages/solid-doc-site/src/pages/ColumnsPage/switchAt.tsx
packages/solid/src/columns.tsx
packages/solid/src/typeUtils.tsx
stories/columns/Columns.stories.tsx
stories/columns/argTypes.ts

Deperecates the old columns prop and adds the prefered colCount prop
re #2207

feat(columns): move to using colCount prop

---

packages/css/src/components/inline-cluster.css
packages/css/src/components/inline.css
packages/inline-cluster/__tests__/__snapshots__/inlineCluster.test.tsx.snap
packages/inline-cluster/__tests__/inlineCluster.test.tsx
packages/inline-cluster/src/index.tsx
packages/inline/__tests__/__snapshots__/inline.test.tsx.snap
packages/inline/__tests__/inline.test.tsx
packages/inline/src/index.tsx
packages/solid-doc-site/src/pages/InlineClusterPage/justify.tsx
packages/solid/src/inline-cluster.tsx
packages/solid/src/inline.tsx
stories/inline-cluster/InlineCluster.stories.tsx
stories/inline-cluster/argTypes.ts
stories/inline/Inline.stories.tsx

feat: add more justification options to inline and inline-cluster

---

packages/css/src/components/padbox.css

This starts the process to allow padding to be added to each of the components instead of stuck to
the padbox
#2207

feat(css): add padding options to the css
